// Mocks generated by Mockito from annotations
// in Lore/test/lore_console_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:convert' as _i2;
import 'dart:io' as _i7;

import 'package:lore/artifact.dart' as _i5;
import 'package:lore/remark.dart' as _i6;
import 'package:lore/repo/lore_repo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEncoding_0 extends _i1.SmartFake implements _i2.Encoding {
  _FakeEncoding_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoreRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoreRepo extends _i1.Mock implements _i3.LoreRepo {
  MockLoreRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Artifact?> loadArtifact(String? md5sum) => (super.noSuchMethod(
        Invocation.method(
          #loadArtifact,
          [md5sum],
        ),
        returnValue: _i4.Future<_i5.Artifact?>.value(),
      ) as _i4.Future<_i5.Artifact?>);

  @override
  _i4.Future<void> saveArtifact(_i5.Artifact? artifact) => (super.noSuchMethod(
        Invocation.method(
          #saveArtifact,
          [artifact],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Remark>> loadRemarks({required String? md5sum}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRemarks,
          [],
          {#md5sum: md5sum},
        ),
        returnValue: _i4.Future<List<_i6.Remark>>.value(<_i6.Remark>[]),
      ) as _i4.Future<List<_i6.Remark>>);

  @override
  _i4.Future<void> saveRemark({
    required String? remark,
    required String? md5sum,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRemark,
          [],
          {
            #remark: remark,
            #md5sum: md5sum,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRemark({required _i6.Remark? remark}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRemark,
          [],
          {#remark: remark},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addToFavorites({
    required _i5.Artifact? artifact,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [],
          {
            #artifact: artifact,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromFavorites({
    required _i5.Artifact? artifact,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [],
          {
            #artifact: artifact,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Artifact>> loadFavoritesArtifacts(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFavoritesArtifacts,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<List<_i5.Artifact>>.value(<_i5.Artifact>[]),
      ) as _i4.Future<List<_i5.Artifact>>);

  @override
  _i4.Future<String?> loginWithJwt(String? jwt) => (super.noSuchMethod(
        Invocation.method(
          #loginWithJwt,
          [jwt],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [IOSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOSink extends _i1.Mock implements _i7.IOSink {
  MockIOSink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Encoding get encoding => (super.noSuchMethod(
        Invocation.getter(#encoding),
        returnValue: _FakeEncoding_0(
          this,
          Invocation.getter(#encoding),
        ),
      ) as _i2.Encoding);

  @override
  _i4.Future<dynamic> get done => (super.noSuchMethod(
        Invocation.getter(#done),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  set encoding(_i2.Encoding? value) => super.noSuchMethod(
        Invocation.setter(
          #encoding,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(List<int>? data) => super.noSuchMethod(
        Invocation.method(
          #add,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void write(Object? object) => super.noSuchMethod(
        Invocation.method(
          #write,
          [object],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeAll(
    Iterable<dynamic>? objects, [
    String? separator = '',
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAll,
          [
            objects,
            separator,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeln([Object? object = '']) => super.noSuchMethod(
        Invocation.method(
          #writeln,
          [object],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeCharCode(int? charCode) => super.noSuchMethod(
        Invocation.method(
          #writeCharCode,
          [charCode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<dynamic> addStream(_i4.Stream<List<int>>? stream) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStream,
          [stream],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
