#!/bin/bash

# Exit on any error
set -e

echo "Building Lore Chrome Extension..."

# Make sure the script is executable
chmod +x $(dirname "$0")/build_extension.sh

# Check for Auth0 configuration
if [ -z "$AUTH0_DOMAIN" ] || [ -z "$AUTH0_CLIENT_ID" ]; then
    echo "Auth0 configuration missing. Please set the following environment variables:"
    echo "  AUTH0_DOMAIN - Your Auth0 domain (e.g., your-tenant.auth0.com)"
    echo "  AUTH0_CLIENT_ID - Your Auth0 client ID"
    echo ""
    echo "Example:"
    echo "  AUTH0_DOMAIN=your-tenant.auth0.com AUTH0_CLIENT_ID=your-client-id ./build_extension.sh"
    exit 1
fi

# Create the auth0.env file for Flutter to read
echo "Creating Auth0 configuration file..."
cat > chrome_extension/lib/auth0_config.dart << EOF
// This file is auto-generated by the build_extension.sh script
// Do not modify manually

const String auth0Domain = '$AUTH0_DOMAIN';
const String auth0ClientId = '$AUTH0_CLIENT_ID';
const String auth0Audience = '$AUTH0_AUDIENCE';
EOF

# Update the manifest.json with Auth0 client ID
echo "Updating manifest.json with Auth0 client ID..."
sed -i "s/\${AUTH0_CLIENT_ID}/$AUTH0_CLIENT_ID/g" chrome_extension/manifest.json

# Build Flutter web app for chrome extension
echo "Building Flutter web app for Chrome extension..."
flutter build web --web-renderer html --csp --dart-define=Dart2jsOptimization=O4 --base-href / --output=build/chrome_extension

# Create directory structure for Chrome extension
echo "Creating Chrome extension structure..."
mkdir -p build/chrome_extension/icons

# Copy the manifest file
echo "Copying manifest.json..."
cp chrome_extension/manifest.json build/chrome_extension/

# Copy the app icon to the extension directory
echo "Copying app icons..."
cp assets/Lore_app_icon.png build/chrome_extension/icons/Icon-128.png

# Convert the main icon to different sizes
echo "Creating icon sizes..."
convert build/chrome_extension/icons/Icon-128.png -resize 16x16 build/chrome_extension/icons/Icon-16.png
convert build/chrome_extension/icons/Icon-128.png -resize 32x32 build/chrome_extension/icons/Icon-32.png
convert build/chrome_extension/icons/Icon-128.png -resize 48x48 build/chrome_extension/icons/Icon-48.png

# Make the extension package
echo "Creating extension package..."
cd build
zip -r lore_extension.zip chrome_extension/
cd ..

echo "Chrome extension built successfully! Extension package is at build/lore_extension.zip"
echo "To install the extension in Chrome:"
echo "1. Go to chrome://extensions/"
echo "2. Enable 'Developer mode'"
echo "3. Click 'Load unpacked' and select the build/chrome_extension directory"