// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtBgKR87CF3vUWiSAl7hgeKPKHdTBAENM',
    appId: '1:746892433042:web:79553b13a9532185ccf84b',
    messagingSenderId: '746892433042',
    projectId: 'lore-5b6b8',
    authDomain: 'lore-5b6b8.firebaseapp.com',
    storageBucket: 'lore-5b6b8.appspot.com',
    measurementId: 'G-HGMXLL8HZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDa8AAb-WTtkiXyCPNE2itfdb5Lik_5CE',
    appId: '1:746892433042:android:97209abc4739852fccf84b',
    messagingSenderId: '746892433042',
    projectId: 'lore-5b6b8',
    storageBucket: 'lore-5b6b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWSLyYBw_ybs3SZV46v3lrkmhXJaA29g',
    appId: '1:746892433042:ios:0fedbee4d69e75b0ccf84b',
    messagingSenderId: '746892433042',
    projectId: 'lore-5b6b8',
    storageBucket: 'lore-5b6b8.appspot.com',
    iosClientId: '746892433042-1ia1eq2nherd72oqe98t2bi6jtdfh53r.apps.googleusercontent.com',
    iosBundleId: 'com.example.l2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWSLyYBw_ybs3SZV46v3lrkmhXJaA29g',
    appId: '1:746892433042:ios:0fedbee4d69e75b0ccf84b',
    messagingSenderId: '746892433042',
    projectId: 'lore-5b6b8',
    storageBucket: 'lore-5b6b8.appspot.com',
    iosClientId: '746892433042-1ia1eq2nherd72oqe98t2bi6jtdfh53r.apps.googleusercontent.com',
    iosBundleId: 'com.example.l2',
  );
}
